spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gestion_terrain
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      org.hibernate.SQL: debug
      org.hibernate.type.descriptor.sql: trace
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  mail:
    host: smtp.gmail.com
    port: 587
    username: ensahterrainservice@gmail.com
    password: blwqndxsieahfqms
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          debug: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

# App Properties
com.ensah:
  jwtCookieName: ensah
  jwtSecret: azizMohammedEnsahGestiondeTerrain123456789+2002+2024+1997+1953+1996+21+WYDAD+RSB+MAROC
  jwtExpirationMs: 86400000
